{% set name = "google-cloud-memcache" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-memcache-{{ version }}.tar.gz
  sha256: 4ae11a1d5d35cfdb7c0c1d3bfba49f1bff12539d8a2936f49b76c19367e55548
  patches:
    - 0001-remove-unwanted-packages.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - libcst >=0.2.5
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3

test:
  imports:
    - google.cloud.memcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-memcache
  license: Apache-2.0
  license_file: LICENSE
  summary: Cloud Memorystore for Memached API
  description: |
    Cloud Memorystore for Memached API: Ship performant and highly available
    key value store, compatible with OSS Memcached protocol.
  dev_url: https://github.com/googleapis/python-memcache
  doc_url: https://googleapis.dev/python/memcache/latest/index.html

extra:
  recipe-maintainers:
    - xylar
